name: Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
      - name: Install dependencies
        run: yarn install
      - name: Lint check
        run: yarn lint
      - name: Format check
        run: yarn format
      - name: Run build
        run: yarn build
